name: custom_lint_happy
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  analyzer: ^5.0.0

dev_dependencies:
  custom_lint: ^0.0.16
  custom_lint_builder: ^0.0.16
